---
- name: Start Redis
  service:
    name: redis-server
    state: started

- name: Restart Redis
  service:
    name: redis-server
    state: restarted

- name: Reload Redis
  service:
    name: redis-server
    state: reloaded

- name: Restart php-fpm
  service:
    name: "{{ trellis_redis_php_fpm }}"
    state: restarted
